### PR TITLE
Sync Branch 20240619 mme #6 support dynamic blocks read evaluation graphs and block visibility parameters

### PR DESCRIPTION
**Pull request by mme1950**

### CODE REVIEW

**Comment by DomCR** [comment]
Hi @mme1950,

I'm planning to release the v1 shortly, but before I would like to change the structure of the project, keep an eye on this PR:

- https://github.com/DomCR/ACadSharp/pull/416

If you plan to implement this feature before, let me know and I will hold the changes.

**Comment by mme1950** [comment]
Hi @DomCR,
thank you for your hint. We have synchronized our fork, master and this branch.
So it is ready to merged from our prespective. And would helpful add ths functionality to the main project.
As I mentioned earlier we can read `BlockVisibilityParameter` object that are linked to a (dynamic) block as far as we need it, but without complete understanding; documentation is missing. The implementation is therefore incomplete.
Perhaps we have a chance that someone can provide more information, when this branch is merged.

**Comment by mme1950** [comment]
Hi @DomCR,
"... The implementation is therefore incomplete." means  It works very well so far, but I do not know how to make it complete.
But I would be happy if you agree to merge this branch now.

**Comment by DomCR** [comment]
> Hi @DomCR, "... The implementation is therefore incomplete." means It works very well so far, but I do not know how to make it complete. But I would be happy if you agree to merge this branch now.

I don't mind to merge the changes, they are quite isolated and are not breaking anything, but you need to update your branch so the README doesn't change and fix the functionality issues like the Clone() method.

**Comment by DomCR** [comment]
One last fix in the Clone() method and we are good to go.

**Review by DomCR — APPROVED** [review]

**Pull request merged**
